// Brew Lab export — auto-generated, do not edit manually.
// Exported: 04-13-2026 17:35:59

const exportMeta = {
  "export_datetime": "04-13-2026 17:35:59",
  "app_version": "1.0.0",
  "db_version": "1.0",
  "schema_version": "1.1"
};

const recipeData = [
  {
    "recipe_id": 59,
    "name": "APA - Wizards & Seven Saws",
    "search": "apa - wizards & seven saws 18b american pale ale",
    "style_id": 56,
    "style": "18B American Pale Ale",
    "style_og_min": 1.045,
    "style_og_max": 1.06,
    "style_fg_min": 1.01,
    "style_fg_max": 1.015,
    "style_ibu_min": 30.0,
    "style_ibu_max": 50.0,
    "style_srm_min": 5.0,
    "style_srm_max": 10.0,
    "style_abv_min": 4.5,
    "style_abv_max": 6.2,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0519,
    "fg": 1.0104,
    "abv": 5.45,
    "abv_unit": "%",
    "ibu": 40.0,
    "srm": 4.6,
    "srm_hex": "#FFBF42",
    "bitterness_balance": 1.2,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Balanced",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "Brun'water - APA (new) - Wizards and Seven Saws",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 175.0,
    "sparge_temp_unit": "°F",
    "boil_time": 60.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 60.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.5,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 6.21,
    "strike_volume_unit": "gal",
    "strike_temp": 159.9,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.31,
    "camden_mash_grams": 0.19,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "design rationale in file Modern American Pale Ale 2026.docx\n\nDon't forget to go look at brew day notes for the test batch and adjust accordingly!",
    "notes_label_2": "Process Notes",
    "notes_2": "Adjust hop quantities for aged hops per recipe guideline\nFlameout hops - add and immediately flash chill to 170F then whirlpool hops for 20 minutes\nSprinkle on yeast (no rehydration necessary for ales at 1052)\nDry hop at 85% attenuation, immediately start ramp down to 58F over 24 hours\n  dry hop using weights in bag per my guideline\nIdeally keep hop contact time to 48 hours\nCold crash/lower temperature  after 48 hours of dry hopping\nCold crash for 3 days once crash temp is reached\nKeg after 3 days of cold crashing (purge keg with CO2 first)\nBurst carbonate at 30psi for 24 hours, then pull PRV, put on 12 psi for 12 hours\nFine tune carbonation to 2.5 volumes\n",
    "notes_date": "2026-03-20",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 153.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pale Malt - Am. 2 row",
        "amount": 9.25,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 91.4
      },
      {
        "name": "Munich Malt - Light",
        "amount": 8.0,
        "unit": "oz",
        "max_extract": 37.0,
        "lovibond": 5.7,
        "pct_of_grist": 4.9
      },
      {
        "name": "Crystal Malt - 40 Lovibond",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 40.0,
        "pct_of_grist": 1.9
      },
      {
        "name": "Cara-Pils Malt",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 33.0,
        "lovibond": 1.8,
        "pct_of_grist": 1.9
      }
    ],
    "hops": [
      {
        "name": "Warrior",
        "amount": 0.49,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.143,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Boil",
        "time": 15,
        "time_unit": "min",
        "time_in_minutes": 15.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 0.6,
        "unit": "oz",
        "usage": "Flameout",
        "time": 0,
        "time_unit": "min",
        "time_in_minutes": 0.0,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Flameout",
        "time": 0,
        "time_unit": "min",
        "time_in_minutes": 0.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 0.65,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.6,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 1.5,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Idaho 7",
        "amount": 3.5,
        "unit": "g",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.125,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Strata",
        "amount": 3.5,
        "unit": "g",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.125,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.5,
        "unit": "tablets",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "WYeast Nutrient",
        "amount": 2.2,
        "unit": "g",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "SafAle US-05 — American Ale",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 80.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": []
  },
  {
    "recipe_id": 71,
    "name": "APA - Wizards & Seven Saws (2.5 gallons)",
    "search": "apa - wizards & seven saws (2.5 gallons) 18b american pale ale",
    "style_id": 56,
    "style": "18B American Pale Ale",
    "style_og_min": 1.045,
    "style_og_max": 1.06,
    "style_fg_min": 1.01,
    "style_fg_max": 1.015,
    "style_ibu_min": 30.0,
    "style_ibu_max": 50.0,
    "style_srm_min": 5.0,
    "style_srm_max": 10.0,
    "style_abv_min": 4.5,
    "style_abv_max": 6.2,
    "batch_size": 2.75,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0519,
    "fg": 1.0104,
    "abv": 5.45,
    "abv_unit": "%",
    "ibu": 40.1,
    "srm": 4.6,
    "srm_hex": "#FFBF42",
    "bitterness_balance": 1.4,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Balanced",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "Brun'water - APA (new) - Wizards and Seven Saws (2.75 gallons)",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 175.0,
    "sparge_temp_unit": "°F",
    "boil_time": 60.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 60.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.5,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 3.16,
    "strike_volume_unit": "gal",
    "strike_temp": 159.0,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.16,
    "camden_mash_grams": 0.1,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "design rationale in file Modern American Pale Ale 2026.docx\nstandard 5 gallon batch ratioed by Brew Lab but manually lowered warrior amount to stay at 40 IBU total\n",
    "notes_label_2": "Process Notes",
    "notes_2": "Adjust hop quantities for aged hops per recipe guideline\nFlameout hops - add and immediately flash chill to 170F\nSprinkle on yeast (no rehydration necessary for ales at 1052)\nDry hop at 85% attenuation, immediately start ramp down to 58F over 24 hours\n  dry hop using weights in bag per my guideline (3.7 ounce aged hops, 9.2 ounce weight, which is large shot glass & 2 bolts)\nIdeally keep hop contact time to 48 hours\nCold crash/lower temperature  after 48 hours of dry hopping\nCold crash for 3 days once crash temp is reached\nKeg after 3 days of cold crashing (purge keg with CO2 first)\nBurst carbonate at 30psi for 24 hours, then pull PRV, put on 12 psi for 12 hours\nFine tune carbonation to 2.5 volumes\n",
    "notes_date": "2026-03-20",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": -0.2,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pale Malt - Am. 2 row",
        "amount": 4.85,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 91.4
      },
      {
        "name": "Munich Malt - Light",
        "amount": 4.19,
        "unit": "oz",
        "max_extract": 37.0,
        "lovibond": 5.7,
        "pct_of_grist": 4.9
      },
      {
        "name": "Crystal Malt - 40 Lovibond",
        "amount": 1.57,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 40.0,
        "pct_of_grist": 1.9
      },
      {
        "name": "Cara-Pils Malt",
        "amount": 1.57,
        "unit": "oz",
        "max_extract": 33.0,
        "lovibond": 1.8,
        "pct_of_grist": 1.9
      }
    ],
    "hops": [
      {
        "name": "Warrior",
        "amount": 0.24,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.143,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.26,
        "unit": "oz",
        "usage": "Boil",
        "time": 15,
        "time_unit": "min",
        "time_in_minutes": 15.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 0.31,
        "unit": "oz",
        "usage": "Flameout",
        "time": 0,
        "time_unit": "min",
        "time_in_minutes": 0.0,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.52,
        "unit": "oz",
        "usage": "Flameout",
        "time": 0,
        "time_unit": "min",
        "time_in_minutes": 0.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 0.34,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.31,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Azacca",
        "amount": 0.52,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.134,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.79,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Idaho 7",
        "amount": 1.83,
        "unit": "g",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.125,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Strata",
        "amount": 1.83,
        "unit": "g",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.125,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.25,
        "unit": "tablets",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "WYeast Nutrient",
        "amount": 1.15,
        "unit": "g",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "SafAle US-05 — American Ale",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 80.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": [
      {
        "session_id": 92,
        "session_date": "03-24-2026",
        "brew_date": "03-24-2026",
        "actual_og": 1.051,
        "actual_fg": 1.01,
        "actual_abv": 5.38,
        "actual_abv_unit": "%",
        "apparent_attenuation": 80.4,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 71.7,
        "mash_efficiency_unit": "%",
        "observed_color": "Bronze",
        "brew_day_notes": "Adjust hop usage for aged hops per brewing sessions table\nHad a hard time getting to target 152F mash temp, strike mash temp 150F,  got to 151F by the end;  verified Brew Lab math for strike volume and temp matches Beerbook, think there was a math error on my part converting 0.16 gallons to quarts resulting in a lower strike volume resulting in not enough hot water to set mash temp correctly.\nph = 5.3 (measured by strip) 5.4 (including .1 correction) - close enough to 5.3 target\nOG 1052 by refractometer, tilt 1050, so we'll say 1051\npitched yeast by sprinkling at 8 PM\nVolume = 2.5 gallons, a little low; kettle trub not excessive, Brew Lab strike volume math verified correct; lbs grain is no more than any other small batch recipe I've done, confirmed larger dry hop volume for aged hops would only result in a 1.28 ounce difference in strike water, believe this is to the strike volume math error above.\nBut if we had a math error and had more strike water, OG would be lower than the expected 1052 so consider lowering efficiency to 72% and adjust accordingly?\n3/28 - dry hop at midnight @ 1017 (ideal target was 1016) - dry hop weight was perfect amount for test batch\n3/30 - reached cold crash temps ~8PM\n4/3 - transfer to keg (after 3.5 days) which makes total hop contact time about 4.5 days, 6 Brix which would be 1.007 (it was 1.011 prior to cold crash) so we'll need another check on the refractometer\n4/4 - 6PM - start burst carb at 28psi",
        "tasting_notes": "at kegging - nice aroma & taste but bitter\neasy drinking, starts out bitter but fades quickly as you drink it, orange and pineapple aromstics\nvery good, not sure if anything needs changing",
        "inventory_applied": true,
        "brew_date_dt": "2026-03-24",
        "aged_hops": [
          {
            "name": "Warrior",
            "amount": 0.24,
            "unit": "oz",
            "usage": "Boil",
            "time": 60.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.24,
            "status": "fresh"
          },
          {
            "name": "Citra",
            "amount": 0.26,
            "unit": "oz",
            "usage": "Boil",
            "time": 15.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.26,
            "status": "fresh"
          },
          {
            "name": "Citra",
            "amount": 0.31,
            "unit": "oz",
            "usage": "Whirlpool 170°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.31,
            "status": "fresh"
          },
          {
            "name": "Citra",
            "amount": 0.52,
            "unit": "oz",
            "usage": "Flameout",
            "time": 0.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.52,
            "status": "fresh"
          },
          {
            "name": "Citra",
            "amount": 0.79,
            "unit": "oz",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.79,
            "status": "fresh"
          },
          {
            "name": "Azacca",
            "amount": 0.31,
            "unit": "oz",
            "usage": "Flameout",
            "time": 0.0,
            "time_unit": "min",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 0.49,
            "status": "adjusted"
          },
          {
            "name": "Azacca",
            "amount": 0.34,
            "unit": "oz",
            "usage": "Whirlpool 170°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 0.53,
            "status": "adjusted"
          },
          {
            "name": "Azacca",
            "amount": 0.52,
            "unit": "oz",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 0.82,
            "status": "adjusted"
          },
          {
            "name": "Strata",
            "amount": 1.83,
            "unit": "g",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2020,
            "hemisphere": "Northern",
            "age_years": 5.6,
            "adjusted_amount": 3.1,
            "status": "adjusted_very_old"
          },
          {
            "name": "Idaho 7",
            "amount": 1.83,
            "unit": "g",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 2.87,
            "status": "adjusted"
          }
        ]
      }
    ]
  },
  {
    "recipe_id": 66,
    "name": "Dark Belgian Ale",
    "search": "dark belgian ale 26b belgian dubbel",
    "style_id": 90,
    "style": "26B Belgian Dubbel",
    "style_og_min": 1.062,
    "style_og_max": 1.075,
    "style_fg_min": 1.008,
    "style_fg_max": 1.018,
    "style_ibu_min": 15.0,
    "style_ibu_max": 25.0,
    "style_srm_min": 10.0,
    "style_srm_max": 17.0,
    "style_abv_min": 6.0,
    "style_abv_max": 7.6,
    "batch_size": 2.75,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0572,
    "fg": 1.0057,
    "abv": 6.76,
    "abv_unit": "%",
    "ibu": 25.4,
    "srm": 23.1,
    "srm_hex": "#952D00",
    "bitterness_balance": 52.1,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "Brun'water - Dark Belgian Ale",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 175.0,
    "sparge_temp_unit": "°F",
    "boil_time": 90.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 90.0,
    "fermentation_temp": 64.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 3.0,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 3.7,
    "strike_volume_unit": "gal",
    "strike_temp": 158.5,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.19,
    "camden_mash_grams": 0.12,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "This was a recipe design to a) make something quick, b) use the BE-134 yeast and c) use up anything I have and not get anything new\nRecipe designed on Gemini session - summary is in google docs\nTarget is really a sessionable dark Belgian ale not 100% suited to any particular style although it's marginally close a Dubbel\nSince we are using older dry yeast, we will want to rehydrate the yeast for 15 minutes before adding to the starter\n  prevents osmotic shock in old yeast; rehydration gives the yeast some time to revitalize themselves (or at least this is what AI says :-))\n",
    "notes_label_2": "Process Notes",
    "notes_2": "Fermentation Schedule\n  Pitch at 64°F and hold until fermentation is 1/3 complete (Restrains harsh phenolic (spicy) and fusel alcohol flavors, securing a clean base)\n  Raise temperature by 1° every 12 hours over the next 3 days to reach 70°F (Encourages desirable fruity esters).\n  Hold at 70° until FG is stable (Reach full attenuation)",
    "notes_date": "unknown",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": -0.2,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pillsner Malt - SPM",
        "amount": 4.5,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 79.1
      },
      {
        "name": "Victory Malt",
        "amount": 8.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 28.0,
        "pct_of_grist": 8.8
      },
      {
        "name": "Crystal Malt - English",
        "amount": 4.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 60.0,
        "pct_of_grist": 4.4
      },
      {
        "name": "Midnight Wheat",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 29.0,
        "lovibond": 550.0,
        "pct_of_grist": 3.3
      },
      {
        "name": "Cara Helles",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 31.0,
        "lovibond": 9.9,
        "pct_of_grist": 3.3
      },
      {
        "name": "Crystal Malt - 120 Lovibond",
        "amount": 1.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 120.0,
        "pct_of_grist": 1.1
      }
    ],
    "hops": [
      {
        "name": "Perle",
        "amount": 0.4,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.071,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Saaz-Czech",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.024,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Sugar - Corn",
        "amount": 3.0,
        "unit": "oz",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      },
      {
        "name": "Yeast Nutrient",
        "amount": 1.5,
        "unit": "tsp",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      },
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.25,
        "unit": "tablets",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "SafAle BE-134 — Belgian Saison",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 90.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": [
      {
        "session_id": 96,
        "session_date": "11-22-2025",
        "brew_date": null,
        "actual_og": 1.055,
        "actual_fg": 1.009,
        "actual_abv": 6.04,
        "actual_abv_unit": "%",
        "apparent_attenuation": 83.6,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 63.6,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  },
  {
    "recipe_id": 72,
    "name": "Dark Mild #7",
    "search": "dark mild #7 13a dark mild",
    "style_id": 38,
    "style": "13A Dark Mild",
    "style_og_min": 1.03,
    "style_og_max": 1.038,
    "style_fg_min": 1.008,
    "style_fg_max": 1.013,
    "style_ibu_min": 10.0,
    "style_ibu_max": 25.0,
    "style_srm_min": 12.0,
    "style_srm_max": 25.0,
    "style_abv_min": 3.0,
    "style_abv_max": 3.8,
    "batch_size": 2.75,
    "batch_size_unit": "gal",
    "efficiency": 72.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0315,
    "fg": 1.0085,
    "abv": 3.02,
    "abv_unit": "%",
    "ibu": 21.7,
    "srm": 13.0,
    "srm_hex": "#CF6900",
    "bitterness_balance": 33.8,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "per special Brun'water file",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 170.0,
    "sparge_temp_unit": "°F",
    "boil_time": 60.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 60.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.1,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 3.03,
    "strike_volume_unit": "gal",
    "strike_temp": 158.7,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.15,
    "camden_mash_grams": 0.09,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "New version based on DRC without chocolate - see google drive file Dark Mild Recipe w/DRC\nFor the initial version, no coloring grains till we see what the DRC does, then consider some midnight wheat for coloring per the above document.",
    "notes_label_2": "Process Notes",
    "notes_2": "only process change will be to dry hop at 85% attenuation for 2 days per my guidelines",
    "notes_date": "2026-03-20",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 154.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": -0.2,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pale Malt - Marris Otter",
        "amount": 38.0,
        "unit": "oz",
        "max_extract": 37.0,
        "lovibond": 2.5,
        "pct_of_grist": 71.0
      },
      {
        "name": "Biscuit Malt",
        "amount": 5.5,
        "unit": "oz",
        "max_extract": 35.0,
        "lovibond": 24.0,
        "pct_of_grist": 10.3
      },
      {
        "name": "Crystal Malt - Double Roasted (DRC)",
        "amount": 4.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 112.0,
        "pct_of_grist": 7.5
      },
      {
        "name": "Crystal Malt - 120 Lovibond",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 34.0,
        "lovibond": 120.0,
        "pct_of_grist": 5.6
      },
      {
        "name": "Torrified Wheat",
        "amount": 3.0,
        "unit": "oz",
        "max_extract": 29.0,
        "lovibond": 1.0,
        "pct_of_grist": 5.6
      }
    ],
    "hops": [
      {
        "name": "Kent Goldings",
        "amount": 0.33,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.043,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Kent Goldings",
        "amount": 0.2,
        "unit": "oz",
        "usage": "Boil",
        "time": 30,
        "time_unit": "min",
        "time_in_minutes": 30.0,
        "alpha_acid": 0.043,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Kent Goldings",
        "amount": 0.25,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.043,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Kent Goldings",
        "amount": 0.25,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.043,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "WYeast Nutrient",
        "amount": 1.1,
        "unit": "g",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.25,
        "unit": "tablets",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "Wyeast 1318 — London Ale III",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 73.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": []
  },
  {
    "recipe_id": 123,
    "name": "Demo",
    "search": "demo 3d czech dark lager",
    "style_id": 11,
    "style": "3D Czech Dark Lager",
    "style_og_min": 1.044,
    "style_og_max": 1.06,
    "style_fg_min": 1.013,
    "style_fg_max": 1.017,
    "style_ibu_min": 18.0,
    "style_ibu_max": 34.0,
    "style_srm_min": 14.0,
    "style_srm_max": 35.0,
    "style_abv_min": 4.4,
    "style_abv_max": 5.8,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 75.0,
    "efficiency_unit": "%",
    "mash_type": "Step Mash (Simple)",
    "strike_vol_method": "full_volume",
    "og": 1.0579,
    "fg": 1.0162,
    "abv": 5.47,
    "abv_unit": "%",
    "ibu": 26.8,
    "srm": 10.6,
    "srm_hex": "#DE7C00",
    "bitterness_balance": -7.4,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Malt Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "Brun'water - Demo Beer",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 172.0,
    "sparge_temp_unit": "°F",
    "boil_time": 90.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 90.0,
    "fermentation_temp": 58.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.0,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 5.73,
    "strike_volume_unit": "gal",
    "strike_temp": 126.9,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.29,
    "camden_mash_grams": 0.18,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "recipe designed for demonstration and test purposes\ngoal is to make a traditional dark lager with a bit of extra dryness from the honey and a citrus/topical punch and aroma ",
    "notes_label_2": "Process Notes",
    "notes_2": "Chill rapidly to fermentation temperature and hold till fermentation is complete\ngradually raise temp to 68 and hold for 2 day diacetyl rest\ncold crash 3 days\ncarbonate by rolling  till it's done",
    "notes_date": "2026-04-12",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Protein Rest",
        "temp_f": 122.0,
        "temp_unit": "°F",
        "time_min": 20.0,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "adjustment_gal": -1.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 3,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pilsner Malt",
        "amount": 9.0,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 86.8
      },
      {
        "name": "Munich Malt - Dark",
        "amount": 16.0,
        "unit": "oz",
        "max_extract": 37.0,
        "lovibond": 8.5,
        "pct_of_grist": 9.6
      },
      {
        "name": "Cara Munich I",
        "amount": 0.25,
        "unit": "lbs",
        "max_extract": 33.0,
        "lovibond": 34.5,
        "pct_of_grist": 2.4
      },
      {
        "name": "Carafa Special III",
        "amount": 56.0,
        "unit": "g",
        "max_extract": 32.0,
        "lovibond": 470.0,
        "pct_of_grist": 1.2
      }
    ],
    "hops": [
      {
        "name": "Perle",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.092,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Saaz-Czech",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.038,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Spalt",
        "amount": 0.25,
        "unit": "oz",
        "usage": "Boil",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.039,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.75,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.122,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "El Dorado",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.112,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.75,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.122,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "El Dorado",
        "amount": 0.5,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.112,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.5,
        "unit": "tablets",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "Yeast Nutrient",
        "amount": 2.0,
        "unit": "tsp",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "Honey",
        "amount": 8.0,
        "unit": "oz",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      }
    ],
    "yeast": [
      {
        "name": "Wyeast 2278 — Czech Pils",
        "amount": 1.0,
        "unit": "Smack Pack",
        "attenuation": 72.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": [
      {
        "session_id": 111,
        "session_date": "04-10-2026",
        "brew_date": "04-10-2026",
        "actual_og": 1.052,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 47.4,
        "mash_efficiency_unit": "%",
        "observed_color": "Closer to Black than Brown",
        "brew_day_notes": "Same approach as the previous brew but now I have to use up some old hops\n\nAnd this time we'll try burst carbonating for 24 hours, pull PRV and reset to 12 psi serving pressure",
        "tasting_notes": "We'll have to see if the hop amount change kicks up that citrus/tropical punch I was looking for in the finish",
        "inventory_applied": false,
        "brew_date_dt": "2026-04-10",
        "aged_hops": [
          {
            "name": "Saaz-Czech",
            "amount": 0.5,
            "unit": "oz",
            "usage": "Boil",
            "time": 60.0,
            "time_unit": "min",
            "crop_year": 2023,
            "hemisphere": "Northern",
            "age_years": 2.6,
            "adjusted_amount": 0.61,
            "status": "adjusted"
          },
          {
            "name": "Spalt",
            "amount": 0.25,
            "unit": "oz",
            "usage": "Boil",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.25,
            "status": "fresh"
          },
          {
            "name": "Perle",
            "amount": 0.5,
            "unit": "oz",
            "usage": "Boil",
            "time": 60.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.5,
            "status": "fresh"
          },
          {
            "name": "El Dorado",
            "amount": 0.5,
            "unit": "oz",
            "usage": "Whirlpool 170°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 0.79,
            "status": "adjusted"
          },
          {
            "name": "El Dorado",
            "amount": 0.5,
            "unit": "oz",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 4.6,
            "adjusted_amount": 0.79,
            "status": "adjusted"
          },
          {
            "name": "Citra",
            "amount": 0.75,
            "unit": "oz",
            "usage": "Dry Hop",
            "time": 2.0,
            "time_unit": "days",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.75,
            "status": "fresh"
          },
          {
            "name": "Citra",
            "amount": 0.75,
            "unit": "oz",
            "usage": "Whirlpool 170°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 0.75,
            "status": "fresh"
          }
        ]
      },
      {
        "session_id": 110,
        "session_date": "04-04-2026",
        "brew_date": null,
        "actual_og": 1.051,
        "actual_fg": 1.01,
        "actual_abv": 5.38,
        "actual_abv_unit": "%",
        "apparent_attenuation": 80.4,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 46.0,
        "mash_efficiency_unit": "%",
        "observed_color": "Dark Brown",
        "brew_day_notes": "every thing went as expected\nmash ph 5.4\nfinal volume in ferment 5.25 gallons as expected",
        "tasting_notes": "As interesting as this beer would be, I'm not sure I want to taste it.",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  },
  {
    "recipe_id": 46,
    "name": "East Coast Pilsner",
    "search": "east coast pilsner 5d german pils",
    "style_id": 18,
    "style": "5D German Pils",
    "style_og_min": 1.044,
    "style_og_max": 1.05,
    "style_fg_min": 1.008,
    "style_fg_max": 1.013,
    "style_ibu_min": 22.0,
    "style_ibu_max": 40.0,
    "style_srm_min": 2.0,
    "style_srm_max": 5.0,
    "style_abv_min": 4.4,
    "style_abv_max": 5.2,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0504,
    "fg": 1.0106,
    "abv": 5.22,
    "abv_unit": "%",
    "ibu": 40.2,
    "srm": 3.5,
    "srm_hex": "#FFCA5A",
    "bitterness_balance": 20.9,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "per Brun'water - East Coast Pilsner",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 176.0,
    "sparge_temp_unit": "°F",
    "boil_time": 90.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 90.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.4,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 6.71,
    "strike_volume_unit": "gal",
    "strike_temp": 158.2,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.34,
    "camden_mash_grams": 0.21,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "Used a very old package of Diamond Lager yeast from Walter",
    "notes_label_2": "Process Notes",
    "notes_2": "",
    "notes_date": "",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Pillsner Malt - SPM",
        "amount": 146.0,
        "unit": "oz",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 92.4
      },
      {
        "name": "Flaked Oats",
        "amount": 0.5,
        "unit": "lbs",
        "max_extract": 33.0,
        "lovibond": 2.2,
        "pct_of_grist": 5.1
      },
      {
        "name": "Cara-Pils Malt",
        "amount": 4.0,
        "unit": "oz",
        "max_extract": 33.0,
        "lovibond": 1.8,
        "pct_of_grist": 2.5
      }
    ],
    "hops": [
      {
        "name": "Warrior",
        "amount": 0.2,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.147,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 1.1,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Mosaic",
        "amount": 0.4,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.112,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.75,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Citra",
        "amount": 0.75,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.138,
        "hop_form": "Pellet",
        "crop_year": 2025,
        "hemisphere": "Northern"
      },
      {
        "name": "Idaho 7",
        "amount": 1.85,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.125,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "Mosaic",
        "amount": 1.5,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 2,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.112,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.5,
        "unit": "tablets",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "WYeast Nutrient",
        "amount": 2.2,
        "unit": "g",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "Other",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 79.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": []
  },
  {
    "recipe_id": 97,
    "name": "Munich Dunkel",
    "search": "munich dunkel 8a munich dunkel",
    "style_id": 24,
    "style": "8A Munich Dunkel",
    "style_og_min": 1.048,
    "style_og_max": 1.056,
    "style_fg_min": 1.01,
    "style_fg_max": 1.016,
    "style_ibu_min": 18.0,
    "style_ibu_max": 28.0,
    "style_srm_min": 14.0,
    "style_srm_max": 28.0,
    "style_abv_min": 4.5,
    "style_abv_max": 5.6,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 72.0,
    "efficiency_unit": "%",
    "mash_type": "Hochkurz",
    "strike_vol_method": "full_volume",
    "og": 1.0513,
    "fg": 1.0128,
    "abv": 5.05,
    "abv_unit": "%",
    "ibu": 21.8,
    "srm": 19.2,
    "srm_hex": "#A13800",
    "bitterness_balance": -3.9,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Balanced",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "Brun'water Munich Dunkel 2023 water",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 170.0,
    "sparge_temp_unit": "°F",
    "boil_time": 90.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 90.0,
    "fermentation_temp": 50.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.3,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 5.48,
    "strike_volume_unit": "gal",
    "strike_temp": 154.4,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.27,
    "camden_mash_grams": 0.16,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "Used Wyeast 2308",
    "notes_label_2": "Process Notes",
    "notes_2": "Pitch at 44-46°F then raise temp to 50 over next 36 hours\n",
    "notes_date": "2025-09-23",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Maltose Rest",
        "temp_f": 147.0,
        "temp_unit": "°F",
        "time_min": 30.0,
        "time_unit": "min",
        "time_in_minutes": 30.0,
        "adjustment_gal": -1.25,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Dextrin Rest",
        "temp_f": 160.0,
        "temp_unit": "°F",
        "time_min": 30.0,
        "time_unit": "min",
        "time_in_minutes": 30.0,
        "adjustment_gal": 1.25,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 3,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Munich Malt - Dark",
        "amount": 8.5,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 8.5,
        "pct_of_grist": 82.9
      },
      {
        "name": "Melanoidan Malt",
        "amount": 0.5,
        "unit": "lbs",
        "max_extract": 33.0,
        "lovibond": 35.0,
        "pct_of_grist": 4.9
      },
      {
        "name": "Cara Munich II",
        "amount": 0.5,
        "unit": "lbs",
        "max_extract": 33.3,
        "lovibond": 45.7,
        "pct_of_grist": 4.9
      },
      {
        "name": "Vienna Malt",
        "amount": 0.5,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 3.0,
        "pct_of_grist": 4.9
      },
      {
        "name": "Carafa Special II",
        "amount": 0.25,
        "unit": "lbs",
        "max_extract": 32.0,
        "lovibond": 413.0,
        "pct_of_grist": 2.4
      }
    ],
    "hops": [
      {
        "name": "Spalt",
        "amount": 1.28,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.043,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "WYeast Nutrient",
        "amount": 2.2,
        "unit": "g",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "Whirlfloc Tablet",
        "amount": 0.5,
        "unit": "tablets",
        "time": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0
      }
    ],
    "yeast": [
      {
        "name": "Other",
        "amount": 1.0,
        "unit": "Packet",
        "attenuation": 75.0,
        "attenuation_unit": "%"
      }
    ],
    "sessions": [
      {
        "session_id": 95,
        "session_date": "09-23-2025",
        "brew_date": null,
        "actual_og": 1.052,
        "actual_fg": 1.018,
        "actual_abv": 4.46,
        "actual_abv_unit": "%",
        "apparent_attenuation": 65.4,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 73.0,
        "mash_efficiency_unit": "%",
        "observed_color": "Dark Black",
        "brew_day_notes": "Initial Impressions before carbonating - good body, a little slick and sharp, malty with a slight chocolate roast, might be good!\n\n",
        "tasting_notes": "Compare to Hofbrau Dunkel and Ayinger Dunkel, mine has similar body, is much darker in color and roastier but smoother and a touch less bitter\nCompare to Treehouse, color is the same but a touch less bitter\nI like my less bitter version better but could cut back the roastiness a bit\nCompared to BJCP, this is black versus dark brown and shows some signs of roastiness which is verboten\nOverall, a very nice and enjoyable beer, just a touch past the style guideline in color and roast; chocolate roast overtakes malty, bready notes that are desired\nVery favorable reviews from club mini-comp, scores consistently around 38 from everyone, 1st place out of 3\n",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  },
  {
    "recipe_id": 122,
    "name": "Test13",
    "search": "test13 1a american light lager",
    "style_id": 1,
    "style": "1A American Light Lager",
    "style_og_min": 1.028,
    "style_og_max": 1.04,
    "style_fg_min": 0.998,
    "style_fg_max": 1.008,
    "style_ibu_min": 8.0,
    "style_ibu_max": 12.0,
    "style_srm_min": 2.0,
    "style_srm_max": 3.0,
    "style_abv_min": 2.8,
    "style_abv_max": 4.2,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Single Infusion",
    "strike_vol_method": "full_volume",
    "og": 1.0364,
    "fg": 1.0091,
    "abv": 3.58,
    "abv_unit": "%",
    "ibu": 131.9,
    "srm": 14.5,
    "srm_hex": "#C35900",
    "bitterness_balance": 1132.0,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 170.0,
    "sparge_temp_unit": "°F",
    "boil_time": 60.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 60.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.4,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 6.01,
    "strike_volume_unit": "gal",
    "strike_temp": 156.9,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.3,
    "camden_mash_grams": 0.18,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": null,
    "notes_label_2": "Process Notes",
    "notes_2": null,
    "notes_date": null,
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 60.0,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Golden Promise",
        "amount": 5.0,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.9,
        "pct_of_grist": 71.4
      },
      {
        "name": "Acidulated Malt",
        "amount": 1.0,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 14.3
      },
      {
        "name": "Cara Aroma",
        "amount": 1.0,
        "unit": "lbs",
        "max_extract": 33.0,
        "lovibond": 130.0,
        "pct_of_grist": 14.3
      }
    ],
    "hops": [
      {
        "name": "Azacca",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.15,
        "hop_form": "Pellet",
        "crop_year": 2021,
        "hemisphere": "Northern"
      },
      {
        "name": "CTZ",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 60,
        "time_unit": "min",
        "time_in_minutes": 60.0,
        "alpha_acid": 0.156,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Dry Hop",
        "time": 3,
        "time_unit": "days",
        "time_in_minutes": null,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Honey",
        "amount": 1.0,
        "unit": "oz",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      },
      {
        "name": "Sugar - Brown",
        "amount": 1.0,
        "unit": "oz",
        "time": 15.0,
        "time_unit": "min",
        "time_in_minutes": 15.0
      }
    ],
    "yeast": [],
    "sessions": [
      {
        "session_id": 105,
        "session_date": "04-03-2026",
        "brew_date": "03-07-2029",
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": "2029-03-07",
        "aged_hops": [
          {
            "name": "Azacca",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Boil",
            "time": 60.0,
            "time_unit": "min",
            "crop_year": 2021,
            "hemisphere": "Northern",
            "age_years": 7.5,
            "adjusted_amount": 1.64,
            "status": "adjusted_very_old"
          },
          {
            "name": "CTZ",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Boil",
            "time": 60.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 3.5,
            "adjusted_amount": 1.3,
            "status": "adjusted"
          },
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Dry Hop",
            "time": 3.0,
            "time_unit": "days",
            "crop_year": null,
            "hemisphere": "Northern",
            "age_years": null,
            "adjusted_amount": null,
            "status": "no_crop_year"
          }
        ]
      },
      {
        "session_id": 104,
        "session_date": null,
        "brew_date": null,
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      },
      {
        "session_id": 106,
        "session_date": null,
        "brew_date": null,
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      },
      {
        "session_id": 107,
        "session_date": null,
        "brew_date": null,
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      },
      {
        "session_id": 108,
        "session_date": null,
        "brew_date": null,
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  },
  {
    "recipe_id": 116,
    "name": "recipe with boil, whirl and flameout at 0 mins",
    "search": "recipe with boil, whirl and flameout at 0 mins 1a american light lager",
    "style_id": 1,
    "style": "1A American Light Lager",
    "style_og_min": 1.028,
    "style_og_max": 1.04,
    "style_fg_min": 0.998,
    "style_fg_max": 1.008,
    "style_ibu_min": 8.0,
    "style_ibu_max": 12.0,
    "style_srm_min": 2.0,
    "style_srm_max": 3.0,
    "style_abv_min": 2.8,
    "style_abv_max": 4.2,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Step Mash (Simple)",
    "strike_vol_method": "full_volume",
    "og": 1.0478,
    "fg": 1.012,
    "abv": 4.7,
    "abv_unit": "%",
    "ibu": 37.1,
    "srm": 41.4,
    "srm_hex": "#600000",
    "bitterness_balance": 163.9,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 170.0,
    "sparge_temp_unit": "°F",
    "boil_time": 20.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 20.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.4,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 5.61,
    "strike_volume_unit": "gal",
    "strike_temp": 127.1,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.28,
    "camden_mash_grams": 0.17,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": null,
    "notes_label_2": "Process Notes",
    "notes_2": null,
    "notes_date": null,
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Protein Rest",
        "temp_f": 122.0,
        "temp_unit": "°F",
        "time_min": 3.0,
        "time_unit": "min",
        "time_in_minutes": 3.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Single Infusion",
        "temp_f": 152.0,
        "temp_unit": "°F",
        "time_min": 3.0,
        "time_unit": "min",
        "time_in_minutes": 3.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 3,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 3.0,
        "time_unit": "min",
        "time_in_minutes": 3.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Brown Malt",
        "amount": 9.5,
        "unit": "lbs",
        "max_extract": 32.0,
        "lovibond": 70.0,
        "pct_of_grist": 90.5
      },
      {
        "name": "Acidulated Malt",
        "amount": 1.0,
        "unit": "lbs",
        "max_extract": 37.0,
        "lovibond": 1.8,
        "pct_of_grist": 9.5
      }
    ],
    "hops": [
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 5,
        "time_unit": "min",
        "time_in_minutes": 5.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Flameout",
        "time": 0,
        "time_unit": "min",
        "time_in_minutes": 0.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Challenger",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Whirlpool 180°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Honey",
        "amount": 1.0,
        "unit": "oz",
        "time": 20.0,
        "time_unit": "min",
        "time_in_minutes": 20.0
      },
      {
        "name": "Irish Moss",
        "amount": 1.0,
        "unit": "tsp",
        "time": 8.0,
        "time_unit": "min",
        "time_in_minutes": 8.0
      }
    ],
    "yeast": [],
    "sessions": [
      {
        "session_id": 116,
        "session_date": "04-15-2026",
        "brew_date": null,
        "actual_og": 1.05,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 73.6,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  },
  {
    "recipe_id": 118,
    "name": "recipe with boil, whirl and flameout at 10 mins",
    "search": "recipe with boil, whirl and flameout at 10 mins 1a american light lager",
    "style_id": 1,
    "style": "1A American Light Lager",
    "style_og_min": 1.028,
    "style_og_max": 1.04,
    "style_fg_min": 0.998,
    "style_fg_max": 1.008,
    "style_ibu_min": 8.0,
    "style_ibu_max": 12.0,
    "style_srm_min": 2.0,
    "style_srm_max": 3.0,
    "style_abv_min": 2.8,
    "style_abv_max": 4.2,
    "batch_size": 5.25,
    "batch_size_unit": "gal",
    "efficiency": 73.0,
    "efficiency_unit": "%",
    "mash_type": "Hochkurz",
    "strike_vol_method": "full_volume",
    "og": 1.0427,
    "fg": 1.0107,
    "abv": 4.2,
    "abv_unit": "%",
    "ibu": 38.8,
    "srm": 41.3,
    "srm_hex": "#600000",
    "bitterness_balance": 208.9,
    "bitterness_balance_unit": "%",
    "bitterness_label": "Bitter Leaning",
    "grain_temp": 68.0,
    "grain_temp_unit": "°F",
    "water_treatments": "",
    "sparge_amount": 1.0,
    "sparge_amount_unit": "gal",
    "sparge_temp": 170.0,
    "sparge_temp_unit": "°F",
    "boil_time": 20.0,
    "boil_time_unit": "min",
    "boil_time_in_minutes": 20.0,
    "fermentation_temp": 68.0,
    "fermentation_temp_unit": "°F",
    "carbonation": 2.4,
    "carbonation_unit": "vol CO₂",
    "strike_volume": 5.54,
    "strike_volume_unit": "gal",
    "strike_temp": 150.5,
    "strike_temp_unit": "°F",
    "camden_mash_tablets": 0.28,
    "camden_mash_grams": 0.17,
    "camden_sparge_tablets": 0.05,
    "camden_sparge_grams": 0.03,
    "notes_label_1": "Design Notes",
    "notes_1": "need some notes man",
    "notes_label_2": "Process Notes",
    "notes_2": "second note",
    "notes_date": "2026-04-11",
    "mash_steps": [
      {
        "step_order": 1,
        "step_label": "Maltose Rest",
        "temp_f": 144.0,
        "temp_unit": "°F",
        "time_min": 30.0,
        "time_unit": "min",
        "time_in_minutes": 30.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 2,
        "step_label": "Dextrin Rest",
        "temp_f": 162.0,
        "temp_unit": "°F",
        "time_min": 30.0,
        "time_unit": "min",
        "time_in_minutes": 30.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 3,
        "step_label": "Mash Out",
        "temp_f": 170.0,
        "temp_unit": "°F",
        "time_min": 10.0,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      },
      {
        "step_order": 4,
        "step_label": "Custom",
        "temp_f": 180.0,
        "temp_unit": "°F",
        "time_min": 5.0,
        "time_unit": "min",
        "time_in_minutes": 5.0,
        "adjustment_gal": 0.0,
        "adjustment_unit": "gal"
      }
    ],
    "grains": [
      {
        "name": "Brown Malt",
        "amount": 9.5,
        "unit": "lbs",
        "max_extract": 32.0,
        "lovibond": 70.0,
        "pct_of_grist": 100.0
      }
    ],
    "hops": [
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Boil",
        "time": 5,
        "time_unit": "min",
        "time_in_minutes": 5.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Flameout",
        "time": 10,
        "time_unit": "min",
        "time_in_minutes": 10.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Challenger",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Whirlpool 180°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      },
      {
        "name": "Amarillo",
        "amount": 1.0,
        "unit": "oz",
        "usage": "Whirlpool 170°",
        "time": 20,
        "time_unit": "min",
        "time_in_minutes": 20.0,
        "alpha_acid": 0.084,
        "hop_form": "Pellet",
        "crop_year": null,
        "hemisphere": "Northern"
      }
    ],
    "boil_additions": [
      {
        "name": "Honey",
        "amount": 1.0,
        "unit": "oz",
        "time": 20.0,
        "time_unit": "min",
        "time_in_minutes": 20.0
      },
      {
        "name": "Irish Moss",
        "amount": 1.0,
        "unit": "tsp",
        "time": 8.0,
        "time_unit": "min",
        "time_in_minutes": 8.0
      }
    ],
    "yeast": [],
    "sessions": [
      {
        "session_id": 109,
        "session_date": "04-16-2026",
        "brew_date": "04-11-2026",
        "actual_og": 1.052,
        "actual_fg": 1.0,
        "actual_abv": 6.83,
        "actual_abv_unit": "%",
        "apparent_attenuation": 100.0,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": 86.0,
        "mash_efficiency_unit": "%",
        "observed_color": "eeky",
        "brew_day_notes": "it was",
        "tasting_notes": "icky but good",
        "inventory_applied": false,
        "brew_date_dt": "2026-04-11",
        "aged_hops": [
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Boil",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 1.0,
            "status": "fresh"
          },
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Boil",
            "time": 5.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 1.0,
            "status": "fresh"
          },
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Flameout",
            "time": 10.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 1.0,
            "status": "fresh"
          },
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Whirlpool 170°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 1.0,
            "status": "fresh"
          },
          {
            "name": "Amarillo",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Boil",
            "time": 10.0,
            "time_unit": "min",
            "crop_year": 2025,
            "hemisphere": "Northern",
            "age_years": 0.6,
            "adjusted_amount": 1.0,
            "status": "fresh"
          },
          {
            "name": "Challenger",
            "amount": 1.0,
            "unit": "oz",
            "usage": "Whirlpool 180°",
            "time": 20.0,
            "time_unit": "min",
            "crop_year": 2022,
            "hemisphere": "Northern",
            "age_years": 3.6,
            "adjusted_amount": 1.45,
            "status": "adjusted"
          }
        ]
      },
      {
        "session_id": 103,
        "session_date": null,
        "brew_date": null,
        "actual_og": null,
        "actual_fg": null,
        "actual_abv": null,
        "actual_abv_unit": "%",
        "apparent_attenuation": null,
        "apparent_attenuation_unit": "%",
        "mash_efficiency": null,
        "mash_efficiency_unit": "%",
        "observed_color": "",
        "brew_day_notes": "",
        "tasting_notes": "",
        "inventory_applied": false,
        "brew_date_dt": null,
        "aged_hops": null
      }
    ]
  }
];
